config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :menus, only: [:index] do
    collection do
      get "venues"
      get "events"
      get "places"
      get "by_venue.(:venue)" => :by_venue, as: "menus_by_venue"
      get "by_event.(:event)" => :by_event, as: "menus_by_event"
    end
  end

  root to: "menus#venues"

  get "/import" => "imports#index"
  post "/import_files" => "imports#import_files"
  get "/new_export" => "exports#index"
  get "/send_export" => "exports#send_export"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  has_many :menu_items
end

app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :menu_pages

  scope :by_place_and_date, -> (place, from_date, to_date) {
    where(place: place).where(date: from_date..to_date).all
  }
end

app/models/menu_item.rb
# frozen_string_literal: true

class MenuItem < ApplicationRecord
  belongs_to :menu_page
  belongs_to :dish
end

app/models/menu_page.rb
# frozen_string_literal: true

class MenuPage < ApplicationRecord
  belongs_to :menu
  has_many :menu_items
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exports_controller.rb
# frozen_string_literal: true

class ExportsController < ApplicationController
  # GET /exports
  def index
    @places = Menu.pluck(:place).map { |place| place.upcase if place }.uniq
  end

  # GET /send_export.json
  def send_export
    export_params = params[:export_params]
    from_date = Date.new export_params["from_date(1i)"].to_i,
        export_params["from_date(2i)"].to_i, export_params["from_date(3i)"].to_i
    to_date = Date.new export_params["to_date(1i)"].to_i,
        export_params["to_date(2i)"].to_i, export_params["to_date(3i)"].to_i

    @menus = Menu.by_place_and_date(export_params[:place], from_date, to_date)

    respond_to do |format|
      format.json { send_data @menus.to_json, type: :json, disposition: "attachment",
        filename: "your_export.json", status: :ok }
    end
  end
end

app/controllers/imports_controller.rb
# frozen_string_literal: true

class ImportsController < ApplicationController
  include CSVImporter

  # POST /import_files
  def import_files
    logger_level_backup = ActiveRecord::Base.logger.level
    ActiveRecord::Base.logger.level = :error

    if params[:menu]
      CSVImporter.process(params[:menu].tempfile, "Menu")
    elsif params[:dish]
      CSVImporter.process(params[:dish].tempfile, "Dish")
    elsif params[:menu_page]
      CSVImporter.process(params[:menu_page].tempfile, "MenuPage")
    elsif params[:menu_item]
      CSVImporter.process(params[:menu_item].tempfile, "MenuItem")
    end

    head :ok
  rescue => e
    logger.error e.message
  ensure
    ActiveRecord::Base.logger.level = logger_level_backup
  end


  # GET /imports
  def index
  end
end

app/controllers/menus_controller.rb
# frozen_string_literal: true

class MenusController < ApplicationController
  # GET /events
  def events
    @events = Menu.pluck(:event).map { |event| event.upcase if event }.reject(&:blank?).uniq
  end

  # GET /venues
  def venues
    @venues = Menu.pluck(:venue).map { |venue| venue.upcase if venue }.reject(&:blank?).uniq
  end

  # GET /places
  def places
    @places = Menu.pluck(:place).map { |place| place.upcase if place }.reject(&:blank?).uniq
  end

  # GET /by_venue
  def by_venue
    venue = params[:venue]
    @menus = Menu.where("lower(venue) = ?", venue.downcase).all
  end

  # GET /by_event
  def by_event
    event = params[:event]
    @menus = Menu.where("lower(event) = ?", event.downcase).all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/imports_helper.rb
# frozen_string_literal: true

module ImportsHelper
end

app/helpers/menus_helper.rb
# frozen_string_literal: true

module MenusHelper
end

app/views/exports/index.html.erb
<p>
  Here you can export data to JSON format.<br />
</p>
<br />

<%= form_tag "/send_export", :method => "get",'data-type' => 'json' do %>
  <div class="panel panel-default">
    <div class="panel-heading">Place filter</div>
    <div class="panel-body">
      <p>Note: For huge datasets, you may need to wait a few second for the below drop-down to expand.</p>
      <div class="form-group">
        <%= label_tag :places, "Place", :class => 'control-label col-lg-2' %> 
        <div class="col-lg-10">
          <%= select "export_params", "place", @places, {:prompt => 'Select'}, :style => "width:300px" %>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">Date filter</div>
    <div class="panel-body">
      <div class="form-group">
        <%= label_tag :from_date, "From date", :class => 'control-label col-lg-2' %> 
        <div class="col-lg-10">
          <%= date_select "export_params", "from_date", start_year: 1800, :style => "width:300px" %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :to_date, "To date", :class => 'control-label col-lg-2' %> 
        <div class="col-lg-10">
          <%= date_select "export_params", "to_date", start_year: 1800, :style => "width:300px" %>
        </div>
      </div>
    </div>
  </div>

  <%= hidden_field_tag :format, :json %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= button_tag "Download JSON", :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/imports/index.html.erb
<p>
  You can upload dataset here, but please note that files should be uploaded in sequence,<br />
  starting with Menu.csv and ending with MenuPage.csv file.<br />
</p>
<%= form_tag "/import_files", method: "post", id: "import_files_form" do %>
  <div>1. Menu.csv: <%= file_field_tag "menu", multiple: false %></div>
  <br />
  <div>2. Dish.csv: <%= file_field_tag "dish", multiple: false %></div>
  <br />
  <div>3. MenuPage.csv: <%= file_field_tag "menu_page", multiple: false %></div>
  <br />
  <div>4. MenuItem.csv: <%= file_field_tag "menu_item", multiple: false %></div>
  <br />
<% end %>
<br />

<div id='import_status'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SampleApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">SampleApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Venues", venues_menus_path  %></li>
            <li><%= link_to "Events", events_menus_path  %></li>
            <li><%= link_to "Places", places_menus_path  %></li>
            <li><%= link_to "Import", '/import'  %></li>
            <li><%= link_to "Export", '/new_export'  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/menus/_menu.html.erb
<tr>
  <td><%= link_to menu.id, menus_path(menu) %></td>
  <td><%= menu.name %></td>
  <td><%= menu.sponsor %></td>
  <td><%= menu.event %></td>
  <td><%= menu.venue %></td>
  <td><%= menu.place %></td>
  <td><%= menu.physical_description %></td>
  <td><%= menu.occasion %></td>
  <td><%= menu.notes %></td>
  <td><%= menu.call_number %></td>
  <td><%= menu.keywords %></td>
  <td><%= menu.language %></td>
  <td><%= menu.date %></td>
  <td><%= menu.location %></td>
  <td><%= menu.location_type %></td>
  <td><%= menu.currency %></td>
  <td><%= menu.currency_symbol %></td>
  <td><%= menu.status %></td>
  <td><%=l menu.created_at %></td>
</tr>

app/views/menus/by_event.html.erb
<p id="notice"><%= notice %></p>

<%- model_class = Menu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              events_menus_path, :class => 'btn btn-default'  %>
<br>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sponsor) %></th>
      <th><%= model_class.human_attribute_name(:event) %></th>
      <th><%= model_class.human_attribute_name(:venue) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:physical_description) %></th>
      <th><%= model_class.human_attribute_name(:occasion) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <th><%= model_class.human_attribute_name(:call_number) %></th>
      <th><%= model_class.human_attribute_name(:keywords) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:location_type) %></th>
      <th><%= model_class.human_attribute_name(:currency) %></th>
      <th><%= model_class.human_attribute_name(:currency_symbol) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @menus.each do |menu| %>
      <%= render 'menu', menu: menu %>
    <% end %>
  </tbody>
</table>


<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              events_menus_path, :class => 'btn btn-default'  %>
<br>
<br>

app/views/menus/by_venue.html.erb
<p id="notice"><%= notice %></p>

<%- model_class = Menu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              venues_menus_path, :class => 'btn btn-default'  %>
<br>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sponsor) %></th>
      <th><%= model_class.human_attribute_name(:event) %></th>
      <th><%= model_class.human_attribute_name(:venue) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:physical_description) %></th>
      <th><%= model_class.human_attribute_name(:occasion) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <th><%= model_class.human_attribute_name(:call_number) %></th>
      <th><%= model_class.human_attribute_name(:keywords) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:location_type) %></th>
      <th><%= model_class.human_attribute_name(:currency) %></th>
      <th><%= model_class.human_attribute_name(:currency_symbol) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @menus.each do |menu| %>
      <%= render 'menu', menu: menu %>
    <% end %>
  </tbody>
</table>


<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              venues_menus_path, :class => 'btn btn-default'  %>
<br>
<br>

app/views/menus/events.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Events</h1>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>
<br>
<br>

<% @events.each do |event| %>
  <%= link_to event, menus_by_event_menus_path(event: event) %>
  <br>
<% end %>

<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>
<br>
<br>

app/views/menus/places.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Places</h1>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>
<br>
<br>

<% @places.each do |place| %>
  <%= place %>
  <br>
<% end %>

<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>
<br>
<br>

app/views/menus/venues.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Venues</h1>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>
<br>
<br>

<% @venues.each do |venue| %>
  <%= link_to venue, menus_by_venue_menus_path(venue: venue) %>
  <br>
<% end %>

<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>
<br>
<br>